const BooksData = [
  {
    id: 1,
    title: "It",
    author: "S. King",
    publication_year: 1986,
    category: "Horror",
    description: "A horror novel about a shape-shifting entity.",
    cover_image:
      "https://images.pexels.com/photos/1078983/pexels-photo-1078983.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    rating: 4.2,
  },
  {
    id: 2,
    title: "Dune",
    author: "F. Herbert",
    publication_year: 1965,
    category: "Science Fiction",
    description: "A science fiction novel set in a desert world.",
    cover_image:
      "https://images.pexels.com/photos/173910/pexels-photo-173910.jpeg?auto=compress&cs=tinysrgb&w=600",
    rating: 4.8,
  },
  {
    id: 3,
    title: "1984",
    author: "G. Orwell",
    publication_year: 1949,
    category: "Dystopian",
    description: "A dystopian novel portraying a totalitarian society.",
    cover_image:
      "https://images.pexels.com/photos/12969937/pexels-photo-12969937.jpeg?auto=compress&cs=tinysrgb&w=600",
    rating: 4.4,
  },
  {
    id: 4,
    title: "Pride",
    author: "J. Austen",
    publication_year: 1813,
    category: "Classic",
    description: "A classic novel exploring themes of love and marriage.",
    cover_image:
      "https://images.pexels.com/photos/1172253/pexels-photo-1172253.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    rating: 4.3,
  },
  {
    id: 5,
    title: "Moby",
    author: "H. Melville",
    publication_year: 1851,
    category: "Fiction",
    description: "The epic tale of Captain Ahab's obsession.",
    cover_image:
      "https://images.pexels.com/photos/7539682/pexels-photo-7539682.jpeg?auto=compress&cs=tinysrgb&w=600",
    rating: 3.9,
  },
  {
    id: 6,
    title: "LOTR",
    author: "J.R.R. Tolkien",
    publication_year: 1954,
    category: "Fantasy",
    description: "An epic fantasy saga about the One Ring.",
    cover_image:
      "https://images.pexels.com/photos/1051076/pexels-photo-1051076.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    rating: 4.9,
  },
  {
    id: 7,
    title: "Rye",
    author: "J.D. Salinger",
    publication_year: 1951,
    category: "Fiction",
    description: "A classic coming-of-age novel.",
    cover_image:
      "https://images.pexels.com/photos/12969937/pexels-photo-12969937.jpeg?auto=compress&cs=tinysrgb&w=600",
    rating: 4.1,
  },
  {
    id: 8,
    title: "Hobbit",
    author: "J.R.R. Tolkien",
    publication_year: 1937,
    category: "Fantasy",
    description: "The prequel to LOTR, about Bilbo's journey.",
    cover_image:
      "https://images.pexels.com/photos/3532548/pexels-photo-3532548.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    rating: 4.7,
  },
  {
    id: 9,
    title: "Peace",
    author: "L. Tolstoy",
    publication_year: 1869,
    category: "Historical",
    description: "Depicting Russian society during the Napoleonic era.",
    cover_image:
      "https://images.pexels.com/photos/1172253/pexels-photo-1172253.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    rating: 4.3,
  },
  {
    id: 10,
    title: "Odyssey",
    author: "Homer",
    publication_year: "1820",
    category: "Epic",
    description: "An ancient Greek epic poem about Odysseus.",
    cover_image:
      "https://images.pexels.com/photos/1103970/pexels-photo-1103970.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    rating: 4.0,
  },
  {
    id: 11,
    title: "Hell",
    author: "Dante",
    publication_year: 1320,
    category: "Poetry",
    description: "An epic poem about a journey through Hell.",
    cover_image:
      "https://images.pexels.com/photos/12969937/pexels-photo-12969937.jpeg?auto=compress&cs=tinysrgb&w=600",
    rating: 3.8,
  },
  {
    id: 12,
    title: "Crime",
    author: "F. Dostoevsky",
    publication_year: 1866,
    category: "Classic",
    description: "A psychological thriller about guilt.",
    cover_image:
      "https://images.pexels.com/photos/1172253/pexels-photo-1172253.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    rating: 4.6,
  },
  {
    id: 13,
    title: "Dorian",
    author: "O. Wilde",
    publication_year: 1890,
    category: "Gothic",
    description: "A novel about a man and his portrait.",
    cover_image:
      "https://images.pexels.com/photos/1078983/pexels-photo-1078983.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    rating: 4.0,
  },
  {
    id: 14,
    title: "World",
    author: "A. Huxley",
    publication_year: 1932,
    category: "Dystopian",
    description: "A dystopian vision of a future society.",
    cover_image:
      "https://images.pexels.com/photos/23232336/pexels-photo-23232336/free-photo-of-woman-in-a-costume-and-mask-holding-a-weapon.jpeg?auto=compress&cs=tinysrgb&w=600",
    rating: 3.7,
  },
  {
    id: 15,
    title: "Monte",
    author: "A. Dumas",
    publication_year: 1844,
    category: "Adventure",
    description: "An adventure novel of revenge.",
    cover_image:
      "https://images.pexels.com/photos/1374064/pexels-photo-1374064.jpeg?auto=compress&cs=tinysrgb&w=600",
    rating: 3.9,
  },
  {
    id: 16,
    title: "Anna",
    author: "L. Tolstoy",
    publication_year: 1877,
    category: "Classic",
    description: "A tragic love story in Russian high society.",
    cover_image:
      "https://images.pexels.com/photos/3522880/pexels-photo-3522880.jpeg?auto=compress&cs=tinysrgb&w=600",
    rating: 4.1,
  },
  {
    id: 17,
    title: "Wind",
    author: "M. Mitchell",
    publication_year: 1936,
    category: "Historical",
    description: "A novel set during the American Civil War.",
    cover_image:
      "https://images.pexels.com/photos/301920/pexels-photo-301920.jpeg?auto=compress&cs=tinysrgb&w=600",
    rating: 4.0,
  },
  {
    id: 18,
    title: "Dracula",
    author: "B. Stoker",
    publication_year: 1897,
    category: "Horror",
    description: "A Gothic horror novel about a vampire.",
    cover_image:
      "https://images.pexels.com/photos/5427740/pexels-photo-5427740.jpeg?auto=compress&cs=tinysrgb&w=600",
    rating: 3.9,
  },
  {
    id: 19,
    title: "Call",
    author: "J. London",
    publication_year: 1903,
    category: "Adventure",
    description: "An adventure novel about a domestic dog.",
    cover_image:
      "https://images.pexels.com/photos/1201673/pexels-photo-1201673.jpeg?auto=compress&cs=tinysrgb&w=600",
    rating: 4.6,
  },
  {
    id: 20,
    title: "Stand",
    author: "S. King",
    publication_year: 1978,
    category: "Horror",
    description: "A post-apocalyptic horror novel.",
    cover_image:
      "https://images.pexels.com/photos/782/night-dark-halloween-horror.jpg?auto=compress&cs=tinysrgb&w=600",
    rating: 3.7,
  },
  {
    id: 21,
    title: "Time",
    author: "S. Hawking",
    publication_year: 1988,
    category: "Non-Fiction",
    description: "A popular science book about cosmology.",
    cover_image:
      "https://images.pexels.com/photos/1400031/pexels-photo-1400031.jpeg?auto=compress&cs=tinysrgb&w=600",
    rating: 3.6,
  },
  {
    id: 22,
    title: "Ender",
    author: "O.S. Card",
    publication_year: 1985,
    category: "Science Fiction",
    description: "A military science fiction novel.",
    cover_image:
      "https://images.pexels.com/photos/4355348/pexels-photo-4355348.jpeg?auto=compress&cs=tinysrgb&w=600",
    rating: 3.1,
  },
  {
    id: 23,
    title: "Island",
    author: "D. Defoe",
    publication_year: 1719,
    category: "Adventure",
    description: "A novel about a man shipwrecked.",
    cover_image:
      "https://images.pexels.com/photos/70361/california-parachutists-skydivers-flares-70361.jpeg?auto=compress&cs=tinysrgb&w=600",
    rating: 3.6,
  },
  {
    id: 24,
    title: "Name",
    author: "P. Rothfuss",
    publication_year: 2007,
    category: "Fantasy",
    description: "About a legendary figure's life story.",
    cover_image:
      "https://images.pexels.com/photos/2867164/pexels-photo-2867164.jpeg?auto=compress&cs=tinysrgb&w=600",
    rating: 3.8,
  },
  {
    id: 25,
    title: "Shining",
    author: "S. King",
    publication_year: 1977,
    category: "Horror",
    description: "About a family in an isolated hotel.",
    cover_image:
      "https://images.pexels.com/photos/2486662/pexels-photo-2486662.jpeg?auto=compress&cs=tinysrgb&w=600",
    rating: 2.3,
  },
  {
    id: 26,
    title: "Sapiens",
    author: "Y.N. Harari",
    publication_year: 2011,
    category: "Non-Fiction",
    description: "A survey of human history.",
    cover_image:
      "https://images.pexels.com/photos/4218865/pexels-photo-4218865.jpeg?auto=compress&cs=tinysrgb&w=600",
    rating: 4.5,
  },
  {
    id: 27,
    title: "Crash",
    author: "W. Gibson",
    publication_year: 1984,
    category: "Science Fiction",
    description: "A cyberpunk novel.",
    cover_image:
      "https://images.pexels.com/photos/2781195/pexels-photo-2781195.jpeg?auto=compress&cs=tinysrgb&w=600",
    rating: 3.5,
  },
  {
    id: 28,
    title: "Musk",
    author: "A. Dumas",
    publication_year: 1844,
    category: "Adventure",
    description: "About four musketeers.",
    cover_image:
      "https://images.pexels.com/photos/951076/pexels-photo-951076.jpeg?auto=compress&cs=tinysrgb&w=600",
    rating: 4.2,
  },
  {
    id: 29,
    title: "Kings",
    author: "B. Sanderson",
    publication_year: 2010,
    category: "Fantasy",
    description: "An epic fantasy series.",
    cover_image:
      "https://images.pexels.com/photos/3359734/pexels-photo-3359734.jpeg?auto=compress&cs=tinysrgb&w=600",
    rating: 4.4,
  },
  {
    id: 30,
    title: "House",
    author: "S. Jackson",
    publication_year: 1959,
    category: "Horror",
    description: "About people investigating a haunted house.",
    cover_image:
      "https://images.pexels.com/photos/1270184/pexels-photo-1270184.jpeg?auto=compress&cs=tinysrgb&w=600",
    rating: 4.3,
  },
];

export default BooksData;
